all:
	gcc -o main1 -Wall main1.c -lpthread
	gcc -o main2 -Wall main2.c -lpthread
	gcc -o main3 -Wall main3.c -lpthread
	gcc -o main4 -Wall main4.c -lpthread
	gcc -o main5 -Wall main5.c -lpthread
clean:
	rm -rf main1 main2 main3 main4 main5
